name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPOSITORY: ravencalamitous
  IMAGE_NAME: test-pintu
  IMAGE_TAG: ${{ github.run_number}}
  CLUSTER_NAME: aks-pintu-cluster
  RESOURCE_GROUP: rg-aks-pintu-cluster

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: node app.js
  
  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  
  deploy:
    name: Deploy
    needs: [ test, build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup AKS Cluster
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}

      - name: Find and Replace 
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["kubernetes/*.yaml"]'
          tokenPrefix: __
          tokenSuffix: __

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/ingress.yaml
            kubernetes/service.yaml
